export interface GetUserInfoParams {
  id?: string
  username?: string
  email?: string
  name?: string
  state?: string
  avatar_url?: string
  web_url?: string
  created_at?: string
  is_admin?: boolean
  bio?: string
  location?: unknown
  skype?: string
  linkedin?: string
  twitter?: string
  website_url?: string
  organization?: string
  last_sign_in_at?: string
  confirmed_at?: string
  theme_id?: number
  last_activity_on?: string
  color_scheme_id?: number
  projects_limit?: number
  current_sign_in_at?: string
  identities?: unknown
  can_create_group?: boolean
  can_create_project?: boolean
  two_factor_enabled?: boolean
  external?: boolean
  private_profile?: boolean
  extern_uid?: string
  created_before?: string
  created_after?: string
  with_custom_attributes?: boolean
}
